function(configure_native_plugin target output)
  set_target_properties(${target} PROPERTIES OUTPUT_NAME "${output}"
    INTERPROCEDURAL_OPTIMIZATION_RELEASE ON DEFINE_SYMBOL mod_EXPORTS)
  target_link_libraries(${target} PRIVATE CommonLibSSE::CommonLibSSE)
  target_compile_features(${target} PRIVATE cxx_std_23)
  target_include_directories(${target} PRIVATE "${SKSE_MCP_INCLUDE_DIRS}"
    "${PROJECT_SOURCE_DIR}/include" "${PROJECT_BINARY_DIR}/generated")
  target_compile_definitions(${target} PRIVATE __CMAKE_COMMONLIBSSE_PLUGIN=1
    WIN32_LEAN_AND_MEAN NOMINMAX UNICODE _UNICODE)
  target_compile_options(${target} PRIVATE /permissive- /Zc:preprocessor /EHsc /W4 /utf-8)
  target_link_options(${target} PRIVATE "/PDBALTPATH:%_PDB%")
endfunction()

function(add_native_test name source)
  add_executable(${name}_test "${source}")
  target_include_directories(${name}_test PRIVATE "${PROJECT_SOURCE_DIR}/include")
  target_compile_options(${name}_test PRIVATE /W4)
  add_test(NAME ${name} COMMAND ${name}_test)
  add_dependencies(native_tests ${name}_test)
endfunction()

function(add_native_addons)
  file(GLOB_RECURSE manifests CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/src/addons/addon.json")
  set(names "")
  foreach(manifest IN LISTS manifests)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}")
    file(READ "${manifest}" declaration)
    string(JSON name GET "${declaration}" name)
    if(NOT name MATCHES "^[A-Za-z][A-Za-z0-9_-]*$")
      message(FATAL_ERROR "Invalid add-on name: ${manifest}")
    endif()
    string(TOLOWER "${name}" key)
    if(key IN_LIST names)
      message(FATAL_ERROR "Duplicate add-on name: ${name}")
    endif()
    list(APPEND names "${key}")
    get_filename_component(directory "${manifest}" DIRECTORY)
    file(GLOB_RECURSE sources CONFIGURE_DEPENDS "${directory}/native/*.cpp")
    if(NOT sources)
      message(FATAL_ERROR "Add-on needs .cpp sources in native/: ${manifest}")
    endif()
    set(PLUGIN_BINARY_NAME "${MOD_BINARY_NAME}.${name}")
    configure_file("${PROJECT_SOURCE_DIR}/cmake/plugin_info.cpp.in" "addons/${key}/plugin_info.cpp" @ONLY)
    add_library(addon_${key} SHARED ${sources} "${PROJECT_BINARY_DIR}/addons/${key}/plugin_info.cpp")
    configure_native_plugin(addon_${key} "${PLUGIN_BINARY_NAME}")
    target_precompile_headers(addon_${key} REUSE_FROM mod)
    add_dependencies(native_plugins addon_${key})
    # Each *_test.cpp is an independent test executable, outside the add-on DLL.
    file(GLOB_RECURSE tests CONFIGURE_DEPENDS "${directory}/tests/native/*_test.cpp")
    foreach(source IN LISTS tests)
      file(RELATIVE_PATH test "${directory}/tests/native" "${source}")
      string(REGEX REPLACE "_test\\.cpp$" "" test "${test}")
      string(REGEX REPLACE "[^A-Za-z0-9_]" "_" test "${test}")
      set(test "addon_${key}_${test}")
      add_native_test(${test} "${source}")
      target_include_directories(${test}_test PRIVATE "${directory}/native")
    endforeach()
  endforeach()
endfunction()
