function(configure_native_plugin target output)
  set_target_properties(${target} PROPERTIES OUTPUT_NAME "${output}"
    INTERPROCEDURAL_OPTIMIZATION_RELEASE ON DEFINE_SYMBOL mod_EXPORTS)
  target_link_libraries(${target} PRIVATE CommonLibSSE::CommonLibSSE)
  target_compile_features(${target} PRIVATE cxx_std_23)
  target_include_directories(${target} PRIVATE "${SKSE_MCP_INCLUDE_DIRS}"
    "${PROJECT_SOURCE_DIR}/include" "${PROJECT_BINARY_DIR}/generated")
  target_compile_definitions(${target} PRIVATE __CMAKE_COMMONLIBSSE_PLUGIN=1
    WIN32_LEAN_AND_MEAN NOMINMAX UNICODE _UNICODE)
  target_compile_options(${target} PRIVATE /permissive- /Zc:preprocessor /EHsc /W4 /utf-8)
  target_link_options(${target} PRIVATE "/PDBALTPATH:%_PDB%")
endfunction()

# Analyze only project translation units, without changing release flags or
# consuming MSVC PCHs that were built without their analysis companion files.
function(add_native_analysis target)
  get_target_property(sources ${target} SOURCES)
  list(FILTER sources INCLUDE REGEX "\\.cpp$")
  list(FILTER sources EXCLUDE REGEX "^${PROJECT_BINARY_DIR}/")
  add_library(${target}_analysis OBJECT ${sources})
  set_target_properties(${target}_analysis PROPERTIES EXCLUDE_FROM_ALL TRUE)
  target_link_libraries(${target}_analysis PRIVATE CommonLibSSE::CommonLibSSE)
  target_compile_features(${target}_analysis PRIVATE cxx_std_23)
  foreach(property INCLUDE_DIRECTORIES COMPILE_DEFINITIONS COMPILE_OPTIONS)
    get_target_property(value ${target} ${property})
    if(value)
      set_property(TARGET ${target}_analysis PROPERTY ${property} "${value}")
    endif()
  endforeach()
  get_target_property(type ${target} TYPE)
  if(type STREQUAL "SHARED_LIBRARY")
    target_compile_definitions(${target}_analysis PRIVATE mod_EXPORTS)
    target_compile_options(${target}_analysis PRIVATE "/FI${PROJECT_SOURCE_DIR}/include/PCH.h")
  endif()
  get_target_property(commonlib_includes CommonLibSSE INTERFACE_INCLUDE_DIRECTORIES)
  target_include_directories(${target}_analysis SYSTEM PRIVATE ${commonlib_includes})
  target_compile_options(${target}_analysis PRIVATE /analyze /analyze:external- /WX)
  add_dependencies(native_analysis ${target}_analysis)
endfunction()

function(add_native_test name source)
  add_executable(${name}_test "${source}")
  target_include_directories(${name}_test PRIVATE "${PROJECT_SOURCE_DIR}/include")
  target_compile_options(${name}_test PRIVATE /W4)
  add_test(NAME ${name} COMMAND ${name}_test)
  add_dependencies(native_tests ${name}_test)
endfunction()

function(add_native_addons)
  file(GLOB_RECURSE manifests CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/src/addons/addon.json")
  set(names "")
  foreach(manifest IN LISTS manifests)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}")
    file(READ "${manifest}" declaration)
    string(JSON name GET "${declaration}" name)
    foreach(field name version)
      string(JSON type TYPE "${declaration}" "${field}")
      if(NOT type STREQUAL "STRING")
        message(FATAL_ERROR "${manifest}: ${field} must be a string")
      endif()
    endforeach()
    string(JSON version GET "${declaration}" version)
    string(JSON type TYPE "${declaration}" adapterApiVersion)
    string(JSON ADDON_ADAPTER_API_VERSION GET "${declaration}" adapterApiVersion)
    string(LENGTH "${ADDON_ADAPTER_API_VERSION}" api_length)
    if(NOT type STREQUAL "NUMBER" OR NOT ADDON_ADAPTER_API_VERSION MATCHES "^[1-9][0-9]*$" OR
       api_length GREATER 10 OR ADDON_ADAPTER_API_VERSION GREATER 4294967295)
      message(FATAL_ERROR "Invalid adapter API version: ${manifest}")
    endif()
    set_plugin_version("${version}")
    if(NOT name MATCHES "^[A-Za-z][A-Za-z0-9_-]*$")
      message(FATAL_ERROR "Invalid add-on name: ${manifest}")
    endif()
    string(TOLOWER "${name}" key)
    if(key IN_LIST names)
      message(FATAL_ERROR "Duplicate add-on name: ${name}")
    endif()
    list(APPEND names "${key}")
    get_filename_component(directory "${manifest}" DIRECTORY)
    file(GLOB_RECURSE sources CONFIGURE_DEPENDS "${directory}/native/*.cpp")
    if(NOT sources)
      message(FATAL_ERROR "Add-on needs .cpp sources in native/: ${manifest}")
    endif()
    set(PLUGIN_BINARY_NAME "${MOD_BINARY_NAME}.${name}")
    set(PLUGIN_DISPLAY_NAME_CPP "${MOD_DISPLAY_NAME_CPP} - ${name}")
    configure_file("${PROJECT_SOURCE_DIR}/cmake/plugin_info.cpp.in" "addons/${key}/plugin_info.cpp" @ONLY)
    configure_file("${PROJECT_SOURCE_DIR}/cmake/version.rc.in" "addons/${key}/version.rc" @ONLY)
    configure_file("${PROJECT_SOURCE_DIR}/cmake/AddonInfo.h.in" "addons/${key}/AddonInfo.h" @ONLY)
    add_library(addon_${key} SHARED ${sources} "${PROJECT_BINARY_DIR}/addons/${key}/plugin_info.cpp"
      "${PROJECT_BINARY_DIR}/addons/${key}/version.rc")
    configure_native_plugin(addon_${key} "${PLUGIN_BINARY_NAME}")
    target_include_directories(addon_${key} PRIVATE "${PROJECT_BINARY_DIR}/addons/${key}")
    add_native_analysis(addon_${key})
    target_precompile_headers(addon_${key} REUSE_FROM mod)
    add_dependencies(native_plugins addon_${key})
    # Each *_test.cpp is an independent test executable, outside the add-on DLL.
    file(GLOB_RECURSE tests CONFIGURE_DEPENDS "${directory}/tests/native/*_test.cpp")
    foreach(source IN LISTS tests)
      file(RELATIVE_PATH test "${directory}/tests/native" "${source}")
      string(REGEX REPLACE "_test\\.cpp$" "" test "${test}")
      string(REGEX REPLACE "[^A-Za-z0-9_]" "_" test "${test}")
      set(test "addon_${key}_${test}")
      add_native_test(${test} "${source}")
      target_include_directories(${test}_test PRIVATE "${directory}/native")
      add_native_analysis(${test}_test)
    endforeach()
  endforeach()
endfunction()
