function(configure_native_plugin target output)
  set_target_properties(${target} PROPERTIES OUTPUT_NAME "${output}"
    INTERPROCEDURAL_OPTIMIZATION_RELEASE ON DEFINE_SYMBOL mod_EXPORTS)
  target_link_libraries(${target} PRIVATE CommonLibSSE::CommonLibSSE)
  target_compile_features(${target} PRIVATE cxx_std_23)
  target_include_directories(${target} PRIVATE "${SKSE_MCP_INCLUDE_DIRS}"
    "${PROJECT_SOURCE_DIR}/include" "${PROJECT_BINARY_DIR}/generated")
  target_compile_definitions(${target} PRIVATE __CMAKE_COMMONLIBSSE_PLUGIN=1
    WIN32_LEAN_AND_MEAN NOMINMAX UNICODE _UNICODE)
  target_compile_options(${target} PRIVATE /permissive- /Zc:preprocessor /EHsc /W4 /utf-8)
  target_link_options(${target} PRIVATE "/PDBALTPATH:%_PDB%")
endfunction()

function(add_native_addons)
  file(GLOB_RECURSE manifests CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/src/addons/addon.json")
  set(names "")
  foreach(manifest IN LISTS manifests)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}")
    file(READ "${manifest}" declaration)
    string(JSON name GET "${declaration}" name)
    if(NOT name MATCHES "^[A-Za-z][A-Za-z0-9_-]*$")
      message(FATAL_ERROR "Invalid add-on name: ${manifest}")
    endif()
    string(TOLOWER "${name}" key)
    if(key IN_LIST names)
      message(FATAL_ERROR "Duplicate add-on name: ${name}")
    endif()
    list(APPEND names "${key}")
    get_filename_component(directory "${manifest}" DIRECTORY)
    string(JSON count LENGTH "${declaration}" sources)
    if(count EQUAL 0)
      message(FATAL_ERROR "Add-on needs sources: ${manifest}")
    endif()
    math(EXPR last "${count} - 1")
    set(sources "")
    foreach(index RANGE ${last})
      string(JSON source GET "${declaration}" sources ${index})
      if(IS_ABSOLUTE "${source}" OR source MATCHES "(^|[/\\\\])\\.\\.([/\\\\]|$)")
        message(FATAL_ERROR "Add-on source must stay within its directory: ${source}")
      endif()
      list(APPEND sources "${directory}/${source}")
    endforeach()
    set(PLUGIN_BINARY_NAME "${MOD_BINARY_NAME}.${name}")
    configure_file("${PROJECT_SOURCE_DIR}/cmake/plugin_info.cpp.in" "addons/${key}/plugin_info.cpp" @ONLY)
    add_library(addon_${key} SHARED ${sources} "${PROJECT_BINARY_DIR}/addons/${key}/plugin_info.cpp")
    configure_native_plugin(addon_${key} "${PLUGIN_BINARY_NAME}")
    target_precompile_headers(addon_${key} REUSE_FROM mod)
    add_dependencies(native_plugins addon_${key})
  endforeach()
endfunction()
