function(set_plugin_version version)
  if(NOT "${version}" MATCHES "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(\\.(0|[1-9][0-9]*))?$")
    message(FATAL_ERROR "Invalid release version: ${version}; expected three or four numeric components")
  endif()
  string(REPLACE "." ";" parts "${version}")
  list(LENGTH parts count)
  if(count EQUAL 3)
    list(APPEND parts 0)
  endif()
  set(names MAJOR MINOR PATCH TWEAK)
  set(limits 255 255 4095 15) # SKSE's packed version layout.
  foreach(index RANGE 0 3)
    list(GET parts ${index} part)
    list(GET names ${index} name)
    list(GET limits ${index} limit)
    string(LENGTH "${part}" length)
    if(length GREATER 4 OR part GREATER limit)
      message(FATAL_ERROR "Release version ${version} exceeds SKSE's ${name} limit (${limit})")
    endif()
    set(PLUGIN_VERSION_${name} "${part}" PARENT_SCOPE)
  endforeach()
endfunction()
